import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Poppins } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartProvider } from "../../context/cartcontext";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`antialiased ${poppins.variable} ${montserrat.variable}`}
        >
          <CartProvider>
            <main>
              <Header />
              {children}
              <Toaster
                position="bottom-right"
                toastOptions={{
                  success: {
                    style: {
                      background: "#065f46",
                      color: "#ecfdf5",
                      border: "1px solid #0d9488",
                      borderRadius: "8px",
                      padding: "12px 16px",
                    },
                  },
                  error: {
                    style: {
                      background: "#991b1b",
                      color: "#fee2e2",
                      border: "1px solid #dc2626",
                      borderRadius: "8px",
                      padding: "12px 16px",
                    },
                  },
                }}
              />
            </main>
            <Footer />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
